
exception E

let _ = try raise E with E -> N2t.print_int 42

(* probl√®me, le try se compile en un code avec PUSHGETGLOBAL *)